// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!^QVQPOOO_QQO'#C_OOQO'#Cg'#CgQVQPOOOOQO'#Ch'#ChO|QQO'#CaO!TQQO,58yOOQO-E6e-E6eOOQO-E6f-E6fOOQO1G.e1G.e",
  stateData: "!Y~O_OS~OQQOSPO~OUSOVSOWSOXSO`SOaSObSOcSOdSO~OYTX~P_OYXO~O",
  goto: "q]PPP^PbPPPPPekTQORRUPQRORVRQTPRWT",
  nodeNames: "⚠ Document Text Macro Open Expression Name Number String Operator Close",
  maxTerm: 20,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "7c~RuOX#fXY$WYZ$WZ]#f]^$W^p#fpq$Wqr$irs%ysv#fvw*uwx+gxy/pyz0^z{%]{|%]|}0z}!O%]!O!P1h!P!Q2U!Q![2r![!^#f!^!_$i!_!`3f!`!a$i!a!c#f!c!}4W!}#R#f#R#S4W#S#T#f#T#o4W#o#p5Z#p#q5f#q#r6T#r;'S#f;'S;=`$Q<%lO#fP#kVQPOX#fZ]#f^p#fq#o#f#p;'S#f;'S;=`$Q<%lO#fP$TP;=`<%l#f~$]S_~XY$WYZ$W]^$Wpq$WR$pXXQQPOX#fZ]#f^p#fq!_#f!_!`%]!`#o#f#p;'S#f;'S;=`$Q<%lO#fR%dVXQQPOX#fZ]#f^p#fq#o#f#p;'S#f;'S;=`$Q<%lO#fR&O_QPOX%yXZ&}Z]%y]^&}^p%ypq&}qr%yrs(ks#O%y#O#P)X#P#o%y#o#p&}#p;'S%y;'S;=`*o<%lO%yQ'QVOr&}rs'gs#O&}#O#P'l#P;'S&};'S;=`(e<%lO&}Q'lOWQQ'oRO;'S&};'S;=`'x;=`O&}Q'{WOr&}rs'gs#O&}#O#P'l#P;'S&};'S;=`(e;=`<%l&}<%lO&}Q(hP;=`<%l&}R(rVWQQPOX#fZ]#f^p#fq#o#f#p;'S#f;'S;=`$Q<%lO#fR)^[QPOX%yXZ&}Z]%y]^&}^p%ypq&}q#o%y#o#p&}#p;'S%y;'S;=`*S;=`<%l&}<%lO%yR*VWOr&}rs'gs#O&}#O#P'l#P;'S&};'S;=`(e;=`<%l%y<%lO&}R*rP;=`<%l%yR*zXQPOX#fZ]#f^p#fqv#fvw%]w#o#f#p;'S#f;'S;=`$Q<%lO#fR+l_QPOX+gXZ,kZ]+g]^,k^p+gpq,kqw+gwx(kx#O+g#O#P.S#P#o+g#o#p,k#p;'S+g;'S;=`/j<%lO+gQ,nVOw,kwx'gx#O,k#O#P-T#P;'S,k;'S;=`-|<%lO,kQ-WRO;'S,k;'S;=`-a;=`O,kQ-dWOw,kwx'gx#O,k#O#P-T#P;'S,k;'S;=`-|;=`<%l,k<%lO,kQ.PP;=`<%l,kR.X[QPOX+gXZ,kZ]+g]^,k^p+gpq,kq#o+g#o#p,k#p;'S+g;'S;=`.};=`<%l,k<%lO+gR/QWOw,kwx'gx#O,k#O#P-T#P;'S,k;'S;=`-|;=`<%l+g<%lO,kR/mP;=`<%l+gR/wV`QQPOX#fZ]#f^p#fq#o#f#p;'S#f;'S;=`$Q<%lO#fR0eVaQQPOX#fZ]#f^p#fq#o#f#p;'S#f;'S;=`$Q<%lO#fR1RVbQQPOX#fZ]#f^p#fq#o#f#p;'S#f;'S;=`$Q<%lO#fR1oVcQQPOX#fZ]#f^p#fq#o#f#p;'S#f;'S;=`$Q<%lO#fR2]VdQQPOX#fZ]#f^p#fq#o#f#p;'S#f;'S;=`$Q<%lO#fR2yXVQQPOX#fZ]#f^p#fq!Q#f!Q![2r![#o#f#p;'S#f;'S;=`$Q<%lO#fR3kXQPOX#fZ]#f^p#fq!_#f!_!`%]!`#o#f#p;'S#f;'S;=`$Q<%lO#fR4_^UQQPOX#fZ]#f^p#fq!Q#f!Q![4W![!c#f!c!}4W!}#R#f#R#S4W#S#T#f#T#o4W#p;'S#f;'S;=`$Q<%lO#f~5^P#o#p5a~5fOS~R5kWQPOX#fZ]#f^p#fq#o#f#p#q%]#q;'S#f;'S;=`$Q<%lO#fR6YXQPOX#fZ]#f^p#fq#o#f#p#q#f#q#r6u#r;'S#f;'S;=`$Q<%lO#fR6|VYQQPOX#fZ]#f^p#fq#o#f#p;'S#f;'S;=`$Q<%lO#f",
  tokenizers: [0, 1],
  topRules: {"Document":[0,1]},
  tokenPrec: 0
})
